name: mobile
description: "A lightweight mobile application designed to demonstrate seamless CRUD operations for managing products and categories."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - .env


flutter_native_splash:
  color: "#53B175"
  image: assets/images/logo_splash.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: false
  android_12:
    color: "#53B175"
    image: assets/images/logo_splash.png
    icon_background_color: "#53B175"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
